language: php

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

env:
  - CONTAO_VERSION=~3.5.5

sudo: false

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

# This used to cause corruption due to travis bug travis-ci/travis-ci#4393 - hopefully it works out now.
cache:
  directories:
    - vendor
